# Generated by Django 4.2.16 on 2024-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='Practice_License_Number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customusers',
            name='civil_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
