# Generated by Django 4.2.16 on 2024-11-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pharmacy', 'Pharmacy')], default='doctor', max_length=20),
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customusers')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('prescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.prescription')),
            ],
        ),
    ]
