# Generated by Django 4.2.16 on 2024-11-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customusers_role_prescription_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='type',
            field=models.CharField(choices=[('internal', 'باطنه'), ('surgery', 'جراحة'), ('pediatric', 'أطفال')], default='internal', max_length=50),
        ),
    ]
